# Generated by Django 5.1.1 on 2024-09-07 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0002_book_delete_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='description_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='description_ko',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='description_ky',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='description_kz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='description_por',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='title_fr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='title_ko',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='title_ky',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='title_kz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='title_por',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='title_ru',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
